#!/usr/bin/env bash

path () {
  # usage: path foo.txt
  FILE="$(readlink -f $1)"
  printf "$FILE\ncopied to clipboard\n"
  printf "$FILE" | xsel -bi
}

h () {
  $1 --help | less
}

# the if statement checks if we are on a laptop
# this works for Debian at least, not sure if works for Arch
if [ -d /sys/module/battery ]; then
  night () {
    local temp=${1:-4800}
    local bright=${2:-1}
    redshift -P -O $temp -b $bright > /dev/null
    echo "setting color temperature to $temp"
    echo "setting brightness to $bright"
    echo "if brightness is less than 1, make sure 'dim 1' is done first"
  }
  dim () {
    local FILE=/sys/class/backlight/intel_backlight/brightness
    echo "current brightness is $(cat $FILE)"
    if [ $# -ne 0 ]; then
      echo "setting brightness to $1..."
      sudo su -c "echo $1 > $FILE"
      echo 'done!'
    fi
  }
  bat () {
    echo -n 'current battery level is '
    cat /sys/class/power_supply/BAT0/capacity
  }
fi
